from app.models import db, Ingredient, environment, SCHEMA, Recipe
from sqlalchemy.sql import text


# Adds a demo user, you can add other users here if you want
def seed_relations():
    ingredient1 = Ingredient.query.get(1)
    ingredient2 = Ingredient.query.get(2)
    ingredient3 = Ingredient.query.get(3)
    ingredient4 = Ingredient.query.get(4)
    ingredient5 = Ingredient.query.get(5)
    ingredient6 = Ingredient.query.get(6)
    ingredient7 = Ingredient.query.get(7)
    ingredient8 = Ingredient.query.get(8)
    ingredient9 = Ingredient.query.get(9)
    ingredient10 = Ingredient.query.get(10)
    ingredient11 = Ingredient.query.get(11)
    ingredient12 = Ingredient.query.get(12)
    ingredient13 = Ingredient.query.get(13)
    ingredient14 = Ingredient.query.get(14)
    ingredient15 = Ingredient.query.get(15)
    ingredient16 = Ingredient.query.get(16)
    ingredient17 = Ingredient.query.get(17)
    ingredient18 = Ingredient.query.get(18)
    ingredient19 = Ingredient.query.get(19)
    ingredient20 = Ingredient.query.get(20)
    ingredient21 = Ingredient.query.get(21)
    ingredient22 = Ingredient.query.get(22)
    ingredient23 = Ingredient.query.get(23)
    ingredient24 = Ingredient.query.get(24)
    ingredient25 = Ingredient.query.get(25)
    ingredient26 = Ingredient.query.get(26)
    ingredient27 = Ingredient.query.get(27)
    ingredient28 = Ingredient.query.get(28)
    ingredient29 = Ingredient.query.get(29)
    ingredient30 = Ingredient.query.get(30)
    ingredient31 = Ingredient.query.get(31)
    ingredient32 = Ingredient.query.get(32)
    ingredient33 = Ingredient.query.get(33)
    ingredient34 = Ingredient.query.get(34)

    recipe1 = Recipe.query.get(1)
    recipe2 = Recipe.query.get(2)
    recipe3 = Recipe.query.get(3)
    recipe4 = Recipe.query.get(4)
    recipe5 = Recipe.query.get(5)
    recipe6 = Recipe.query.get(6)
    recipe7 = Recipe.query.get(7)
    recipe8 = Recipe.query.get(8)
    recipe9 = Recipe.query.get(9)
    recipe10 = Recipe.query.get(10)
    recipe11 = Recipe.query.get(11)
    recipe12 = Recipe.query.get(12)
    recipe13 = Recipe.query.get(13)
    recipe14 = Recipe.query.get(14)
    recipe15 = Recipe.query.get(15)
    recipe16 = Recipe.query.get(16)
    recipe17 = Recipe.query.get(17)
    recipe18 = Recipe.query.get(18)
    recipe19 = Recipe.query.get(19)
    recipe20 = Recipe.query.get(20)
    recipe21 = Recipe.query.get(21)
    recipe22 = Recipe.query.get(22)
    recipe23 = Recipe.query.get(23)
    recipe24 = Recipe.query.get(24)
    recipe25 = Recipe.query.get(25)
    recipe26 = Recipe.query.get(26)
    recipe27 = Recipe.query.get(27)
    recipe28 = Recipe.query.get(28)
    recipe29 = Recipe.query.get(29)
    recipe30 = Recipe.query.get(30)
    recipe31 = Recipe.query.get(31)
    recipe32 = Recipe.query.get(32)
    recipe33 = Recipe.query.get(33)
    recipe34 = Recipe.query.get(34)
    recipe35 = Recipe.query.get(35)
    recipe36 = Recipe.query.get(36)
    recipe37 = Recipe.query.get(37)
    recipe38 = Recipe.query.get(38)
    recipe39 = Recipe.query.get(39)
    recipe40 = Recipe.query.get(40)
    recipe41 = Recipe.query.get(41)
    recipe42 = Recipe.query.get(42)
    recipe43 = Recipe.query.get(43)
    recipe44 = Recipe.query.get(44)
    recipe45 = Recipe.query.get(45)
    recipe46 = Recipe.query.get(46)
    recipe47 = Recipe.query.get(47)
    recipe48 = Recipe.query.get(48)
    recipe49 = Recipe.query.get(49)
    recipe50 = Recipe.query.get(50)
    recipe51 = Recipe.query.get(51)
    recipe52 = Recipe.query.get(52)
    recipe53 = Recipe.query.get(53)
    recipe54 = Recipe.query.get(54)
    recipe55 = Recipe.query.get(55)

    recipe1.recipe_ingredients.append(ingredient1)
    recipe1.recipe_ingredients.append(ingredient29)
    recipe1.recipe_ingredients.append(ingredient31)
    recipe31.recipe_ingredients.append(ingredient7)
    recipe31.recipe_ingredients.append(ingredient8)
    recipe3.recipe_ingredients.append(ingredient2)
    recipe18.recipe_ingredients.append(ingredient27)
    recipe18.recipe_ingredients.append(ingredient32)
    recipe18.recipe_ingredients.append(ingredient31)
    recipe18.recipe_ingredients.append(ingredient1)
    recipe18.recipe_ingredients.append(ingredient4)
    recipe51.recipe_ingredients.append(ingredient6)
    recipe55.recipe_ingredients.append(ingredient8)
    recipe26.recipe_ingredients.append(ingredient1)
    recipe26.recipe_ingredients.append(ingredient14)
    recipe26.recipe_ingredients.append(ingredient4)
    recipe26.recipe_ingredients.append(ingredient5)
    recipe36.recipe_ingredients.append(ingredient13)
    recipe36.recipe_ingredients.append(ingredient21)
    recipe9.recipe_ingredients.append(ingredient1)
    recipe9.recipe_ingredients.append(ingredient4)
    recipe9.recipe_ingredients.append(ingredient31)
    recipe44.recipe_ingredients.append(ingredient33)
    recipe44.recipe_ingredients.append(ingredient34)
    recipe11.recipe_ingredients.append(ingredient2)
    recipe11.recipe_ingredients.append(ingredient19)
    recipe11.recipe_ingredients.append(ingredient3)
    recipe11.recipe_ingredients.append(ingredient13)
    recipe11.recipe_ingredients.append(ingredient9)
    recipe11.recipe_ingredients.append(ingredient10)
    recipe11.recipe_ingredients.append(ingredient11)
    recipe11.recipe_ingredients.append(ingredient30)
    recipe11.recipe_ingredients.append(ingredient12)
    recipe12.recipe_ingredients.append(ingredient6)
    recipe12.recipe_ingredients.append(ingredient9)
    recipe12.recipe_ingredients.append(ingredient15)
    recipe12.recipe_ingredients.append(ingredient5)
    recipe12.recipe_ingredients.append(ingredient10)
    recipe12.recipe_ingredients.append(ingredient16)
    recipe12.recipe_ingredients.append(ingredient17)
    recipe12.recipe_ingredients.append(ingredient29)
    recipe12.recipe_ingredients.append(ingredient3)
    recipe13.recipe_ingredients.append(ingredient18)
    recipe13.recipe_ingredients.append(ingredient9)
    recipe13.recipe_ingredients.append(ingredient20)
    recipe13.recipe_ingredients.append(ingredient22)
    recipe13.recipe_ingredients.append(ingredient23)
    recipe13.recipe_ingredients.append(ingredient24)
    recipe13.recipe_ingredients.append(ingredient25)
    recipe14.recipe_ingredients.append(ingredient26)
    recipe14.recipe_ingredients.append(ingredient5)
    recipe14.recipe_ingredients.append(ingredient9)
    recipe14.recipe_ingredients.append(ingredient25)
    recipe14.recipe_ingredients.append(ingredient28)
    recipe14.recipe_ingredients.append(ingredient30)
    recipe14.recipe_ingredients.append(ingredient12)
    recipe15.recipe_ingredients.append(ingredient2)
    recipe15.recipe_ingredients.append(ingredient6)
    recipe15.recipe_ingredients.append(ingredient11)
    recipe15.recipe_ingredients.append(ingredient26)
    recipe15.recipe_ingredients.append(ingredient15)
    recipe16.recipe_ingredients.append(ingredient6)
    recipe16.recipe_ingredients.append(ingredient15)
    recipe16.recipe_ingredients.append(ingredient5)
    recipe16.recipe_ingredients.append(ingredient12)
    recipe16.recipe_ingredients.append(ingredient26)
    recipe17.recipe_ingredients.append(ingredient6)
    recipe17.recipe_ingredients.append(ingredient15)
    recipe17.recipe_ingredients.append(ingredient5)
    recipe17.recipe_ingredients.append(ingredient9)
    recipe17.recipe_ingredients.append(ingredient30)
    recipe17.recipe_ingredients.append(ingredient10)
    recipe4.recipe_ingredients.append(ingredient12)
    recipe4.recipe_ingredients.append(ingredient26)
    recipe4.recipe_ingredients.append(ingredient9)
    recipe19.recipe_ingredients.append(ingredient2)
    recipe19.recipe_ingredients.append(ingredient11)
    recipe19.recipe_ingredients.append(ingredient9)
    recipe19.recipe_ingredients.append(ingredient10)
    recipe19.recipe_ingredients.append(ingredient17)
    recipe19.recipe_ingredients.append(ingredient5)
    recipe19.recipe_ingredients.append(ingredient15)
    recipe19.recipe_ingredients.append(ingredient14)
    recipe19.recipe_ingredients.append(ingredient26)
    recipe19.recipe_ingredients.append(ingredient12)
    recipe20.recipe_ingredients.append(ingredient5)
    recipe20.recipe_ingredients.append(ingredient9)
    recipe20.recipe_ingredients.append(ingredient17)
    recipe20.recipe_ingredients.append(ingredient26)
    recipe20.recipe_ingredients.append(ingredient12)
    recipe21.recipe_ingredients.append(ingredient1)
    recipe21.recipe_ingredients.append(ingredient3)
    recipe21.recipe_ingredients.append(ingredient4)
    recipe21.recipe_ingredients.append(ingredient7)
    recipe22.recipe_ingredients.append(ingredient9)
    recipe22.recipe_ingredients.append(ingredient10)
    recipe22.recipe_ingredients.append(ingredient11)
    recipe22.recipe_ingredients.append(ingredient12)
    recipe22.recipe_ingredients.append(ingredient13)
    recipe22.recipe_ingredients.append(ingredient14)
    recipe22.recipe_ingredients.append(ingredient15)
    recipe22.recipe_ingredients.append(ingredient16)
    recipe23.recipe_ingredients.append(ingredient1)
    recipe23.recipe_ingredients.append(ingredient3)
    recipe23.recipe_ingredients.append(ingredient4)
    recipe23.recipe_ingredients.append(ingredient18)
    recipe23.recipe_ingredients.append(ingredient11)
    recipe23.recipe_ingredients.append(ingredient14)
    recipe23.recipe_ingredients.append(ingredient15)
    recipe24.recipe_ingredients.append(ingredient19)
    recipe24.recipe_ingredients.append(ingredient20)
    recipe24.recipe_ingredients.append(ingredient21)
    recipe24.recipe_ingredients.append(ingredient22)
    recipe24.recipe_ingredients.append(ingredient23)
    recipe24.recipe_ingredients.append(ingredient3)
    recipe24.recipe_ingredients.append(ingredient14)
    recipe24.recipe_ingredients.append(ingredient15)
    recipe24.recipe_ingredients.append(ingredient16)
    recipe24.recipe_ingredients.append(ingredient24)
    recipe25.recipe_ingredients.append(ingredient25)
    recipe25.recipe_ingredients.append(ingredient26)
    recipe25.recipe_ingredients.append(ingredient27)
    recipe25.recipe_ingredients.append(ingredient28)
    recipe25.recipe_ingredients.append(ingredient29)
    recipe25.recipe_ingredients.append(ingredient30)
    recipe25.recipe_ingredients.append(ingredient31)
    recipe25.recipe_ingredients.append(ingredient32)
    recipe7.recipe_ingredients.append(ingredient33)
    recipe7.recipe_ingredients.append(ingredient4)
    recipe7.recipe_ingredients.append(ingredient34)
    recipe7.recipe_ingredients.append(ingredient10)
    recipe7.recipe_ingredients.append(ingredient21)
    recipe7.recipe_ingredients.append(ingredient11)
    recipe7.recipe_ingredients.append(ingredient14)
    recipe7.recipe_ingredients.append(ingredient15)
    recipe27.recipe_ingredients.append(ingredient26)
    recipe29.recipe_ingredients.append(ingredient10)
    recipe2.recipe_ingredients.append(ingredient10)
    recipe32.recipe_ingredients.append(ingredient28)
    recipe32.recipe_ingredients.append(ingredient1)
    recipe32.recipe_ingredients.append(ingredient8)
    recipe32.recipe_ingredients.append(ingredient7)
    recipe32.recipe_ingredients.append(ingredient22)
    recipe32.recipe_ingredients.append(ingredient6)
    recipe32.recipe_ingredients.append(ingredient12)
    recipe32.recipe_ingredients.append(ingredient2)
    recipe33.recipe_ingredients.append(ingredient18)
    recipe33.recipe_ingredients.append(ingredient15)
    recipe33.recipe_ingredients.append(ingredient8)
    recipe33.recipe_ingredients.append(ingredient7)
    recipe33.recipe_ingredients.append(ingredient12)
    recipe33.recipe_ingredients.append(ingredient3)
    recipe33.recipe_ingredients.append(ingredient6)
    recipe33.recipe_ingredients.append(ingredient22)
    recipe33.recipe_ingredients.append(ingredient9)
    recipe33.recipe_ingredients.append(ingredient2)
    recipe34.recipe_ingredients.append(ingredient4)
    recipe34.recipe_ingredients.append(ingredient1)
    recipe34.recipe_ingredients.append(ingredient16)
    recipe34.recipe_ingredients.append(ingredient10)
    recipe34.recipe_ingredients.append(ingredient17)
    recipe34.recipe_ingredients.append(ingredient34)
    recipe34.recipe_ingredients.append(ingredient3)
    recipe34.recipe_ingredients.append(ingredient6)
    recipe34.recipe_ingredients.append(ingredient2)
    recipe35.recipe_ingredients.append(ingredient1)
    recipe35.recipe_ingredients.append(ingredient3)
    recipe35.recipe_ingredients.append(ingredient17)
    recipe35.recipe_ingredients.append(ingredient2)
    recipe8.recipe_ingredients.append(ingredient6)
    recipe8.recipe_ingredients.append(ingredient24)
    recipe37.recipe_ingredients.append(ingredient17)
    recipe38.recipe_ingredients.append(ingredient4)
    recipe39.recipe_ingredients.append(ingredient33)
    recipe40.recipe_ingredients.append(ingredient3)
    recipe41.recipe_ingredients.append(ingredient17)
    recipe42.recipe_ingredients.append(ingredient1)
    recipe43.recipe_ingredients.append(ingredient7)
    recipe43.recipe_ingredients.append(ingredient8)
    recipe10.recipe_ingredients.append(ingredient27)
    recipe10.recipe_ingredients.append(ingredient32)
    recipe10.recipe_ingredients.append(ingredient31)
    recipe10.recipe_ingredients.append(ingredient1)
    recipe10.recipe_ingredients.append(ingredient4)


    db.session.commit()

def undo_relations():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.relates RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM relates"))

    db.session.commit()
